// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBryuF1-SKseA9cu3irDzoObdnekWIPkHY',
    appId: '1:561988576001:web:9c8eeb870248521853b100',
    messagingSenderId: '561988576001',
    projectId: 'myfirstflutterapponredhwak',
    authDomain: 'myfirstflutterapponredhwak.firebaseapp.com',
    storageBucket: 'myfirstflutterapponredhwak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6u1cQHwt0iE38wpoEvDgKk3KkWMaf2Ws',
    appId: '1:561988576001:android:c4a81409c963256853b100',
    messagingSenderId: '561988576001',
    projectId: 'myfirstflutterapponredhwak',
    storageBucket: 'myfirstflutterapponredhwak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKiKQ5PypGxVx7ZfsLTAo_GWiWBgYlYo',
    appId: '1:561988576001:ios:2b74e5f386e320c053b100',
    messagingSenderId: '561988576001',
    projectId: 'myfirstflutterapponredhwak',
    storageBucket: 'myfirstflutterapponredhwak.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKKiKQ5PypGxVx7ZfsLTAo_GWiWBgYlYo',
    appId: '1:561988576001:ios:7077808b17acd33a53b100',
    messagingSenderId: '561988576001',
    projectId: 'myfirstflutterapponredhwak',
    storageBucket: 'myfirstflutterapponredhwak.appspot.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
